add_newline = true
command_timeout = 200
format = """
[â”Œâ”€](bold cyan)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$lua\
$docker_context\
$kubernetes\
$cmd_duration\
$time
[â””â”€](bold cyan)$character"""

[character]
error_symbol = "[âœ—](bold cyan)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold red"
repo_root_format = " [$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = 'fg:green'
symbol = 'ï˜ '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
format     = '[$all_status$ahead_behind]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "x "
up_to_date = ""
untracked  = "! "
modified   = "! "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

# Show command duration if > 2 seconds
[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

# Python version
[python]
symbol = "îˆµ  "
format = '[$symbol$version]($style) '
style = "yellow"

[lua]
symbol = 'î˜  '

# Node.js version
[nodejs]
symbol = "â¬¢ "
format = '[$symbol$version]($style) '
style = "green"

# Rust version
[rust]
symbol = "ðŸ¦€ "
format = '[$symbol$version]($style) '
style = "orange"

# Go version
[golang]
symbol = 'î˜§ '
format = '[$symbol$version]($style) '
style = "cyan"

# Kubernetes context
[kubernetes]
disabled = true
format = '[â˜¸  $context](bold blue) '

# Docker context
[docker_context]
symbol = 'ïŒˆ '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[time]
disabled = false
format = 'ðŸ•™[$time]($style) '
style = "bright-white"
