add_newline = true
command_timeout = 200
format = """
[â”Œâ”€](bold cyan)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$docker_context\
$kubernetes\
$cmd_duration\
$time
[â””â”€](bold cyan)$character"""

[character]
error_symbol = "[âœ—](bold cyan)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold red"
repo_root_format = " [$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

# Show command duration if > 2 seconds
[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

# Python version
[python]
symbol = " "
format = '[$symbol$version]($style) '
style = "yellow"

# Node.js version
[nodejs]
symbol = " "
format = '[$symbol$version]($style) '
style = "green"

# Rust version
[rust]
symbol = " "
format = '[$symbol$version]($style) '
style = "red"

# Go version
[golang]
symbol = " "
format = '[$symbol$version]($style) '
style = "cyan"

# Kubernetes context
[kubernetes]
disabled = false
format = '[âŽˆ $context](bold blue) '

# Docker context
[docker_context]
symbol = " "
format = '[$symbol$context]($style) '
style = "blue"

[time]
disabled = false
format = 'ðŸ•™[$time]($style) '
style = "bright-white"
